name: Docker Image CI

env:
  REGISTRY_NAME: azurearcacr
  CLUSTER_NAME: docker-desktop
  CLUSTER_RESOURCE_GROUP: AzureArc
  NAMESPACE: AzureArcDemo
  APP_NAME: addition
  
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Connet to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.REGISTRY_NAME}}.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        
    - name: Build the Docker image
      run: |
        docker build . --file Addition/Dockerfile --tag ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME }}:${{ github.sha }}
        docker push ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME }}:${{ github.sha }}
        

    - name: Helm Deploy
      uses: vimeda/helm@v1.6.8
      with:
        release: nginx
        namespace: default
        chart: addition-chart
        values: |
          name: addition-chart
        value-files: "values.yaml"
        

        
  
